export const API_ENDPOINTS = {
  ALLERGIES: `/api/allergies`,
  APPOINTMENTS: `/api/appointments`,
  APPOINTMENT_PROFILES: `/api/appointment_profiles`,
  APPOINTMENT_TEMPLATES: `/api/appointment_templates`,
  TELEHEALTH_APPOINTMENTS: `/api/telehealth_appointments`,
  BILLING_PROFILES: `/api/billing_profiles`,

  CLINICAL_NOTE_TEMPLATES: `/api/clinical_note_templates`,

  CONSENT_FORMS: `/api/consent_forms`,
  CUSTOM_APPOINTMENT_FIELDS: `/api/custom_appointment_fields`,
  CUSTOM_DEMOGRAPHICS: `/api/custom_demographics`,
  CUSTOM_VITALS: `/api/custom_vitals`,
  DOCTORS: `/api/doctors`,
  DOCUMENTS: `/api/documents`,
  IFRAME_INTEGRATION: `/api/iframe_integration`,
  //   IMPLANTABLE_DEVICES: `/api/implantable_devices`, || Fitbit and stuff
  INVENTORY_CATEGORIES: `/api/inventory_categories`,
  INVENTORY_VACCINES: `/api/inventory_vaccines`,
  MEDICATIONS: `/api/medications`,
  OFFICES: `/api/offices`,
  PATIENTS: `/api/patients`,
  PATIENT_CCDA: `/api/patients/:id/ccda`,
  PATIENT_QRDA1: `/api/patients/:id/qrda1`,
  PATIENT_ONPATIENT_ACCESS: `/api/patients/:id/onpatient_access`,
  PATIENT_COMMUNICATIONS: `/api/patient_communications`,
  PATIENT_FLAG_TYPES: `/api/patient_flag_types`,
  PATIENT_INTERVENTIONS: `/api/patient_interventions`,
  PATIENT_PHYSICAL_EXAMS: `/api/patient_physical_exams`,
  PATIENT_RISK_ASSESSMENTS: `/api/patient_risk_assessments`,
  PATIENTS_SUMMARY: `/api/patients_summary`,
  //   PROBLEMS: `/api/problems`,
  REMINDER_PROFILES: `/api/reminder_profiles`,

  USERS: `/api/users`,
  //   USER_GROUPS: `/api/user_groups`,
  AUTHORIZE: `/o/authorize`,
  REVOKE_TOKEN: `/o/revoke_token`,
  TOKEN: `/o/token`,
  AMENDMENTS: `/api/amendments`,
  CARE_PLANS: `/api/care_plans`,
  CLAIM_BILLING_NOTES: `/api/claim_billing_notes`,
  CLINICAL_NOTES: `/api/clinical_notes`,
  CLINICAL_NOTE_FIELD_TYPES: `/api/clinical_note_field_types`,
  CLINICAL_NOTE_FIELD_VALUES: `/api/clinical_note_field_values`,
  CUSTOM_INSURANCE_PLAN_NAMES: `/api/custom_insurance_plan_names`,
  ELIGIBILITY_CHECKS: `/api/eligibility_checks`,
  EOBS: `/api/eobs`, // Explanation of Benefits.
  FEE_SCHEDULES: `/api/fee_schedules`,
  INSURANCES: `/api/insurances`,
  LAB_DOCUMENTS: `/api/lab_documents`,
  LAB_ORDERS: `/api/lab_orders`,
  LAB_ORDERS_SUMMARY: `/api/lab_orders_summary`,
  LAB_TESTS: `/api/lab_tests`,
  LAB_RESULTS: `/api/lab_results`,
  LINE_ITEMS: `/api/line_items`,
  MEDICATIONS_APPEND_TO_PHARMACY_NOTE: `/api/medications/:id/append_to_pharmacy_note`,
  MESSAGES: `/api/messages`,
  PATIENT_MESSAGES: `/api/patient_messages`,
  PRESCRIPTION_MESSAGES: `/api/prescription_messages`,
  COMMUNICATION_LOGS: `/api/comm_logs`,
  //   ADD_EXAM_ROOM: `/api/offices/:id/add_exam_room`,
  PATIENT_LAB_RESULTS: `/api/pateint_lab_results`,

  PATIENT_PAYMENTS: `/api/patient_payments`,
  PATIENT_PAYMENT_LOG: `/api/patient_payment_log`,
  PATIENT_VACCINE_RECORDS: `/api/patient_vaccine_records`,

  PROCEDURES: `/api/procedures`,
  SUBLABS: `/api/sublabs`,
  TASKS: `/api/tasks`,
  TASK_CATEGORIES: `/api/task_categories`,
  TASK_NOTES: `/api/task_notes`,
  TASK_TEMPLATES: `/api/task_templates`,
  TASK_STATUSES: `/api/task_statuses`,
  TRANSACTIONS: `/api/transactions`,
};
