const allergenType = {
  BEEF: "Allergy to beef",
  LOBSTER: "Allergy to lobster",
  PORK: "Allergy to pork",
  EGGS: "Allergy to eggs",
  MILK: "Allergy to milk",
  WHEAT: "Allergy to wheat",
  SOY: "Allergy to soy",
  FISH: "Allergy to fish",
  TREE_NUT: "Allergy to tree nuts",
  PEANUT: "Allergy to peanuts",
  SHELLFISH: "Allergy to shellfish",
  SESAME: "Allergy to sesame",
  SULFITES: "Allergy to sulfites",
  MUSTARD: "Allergy to mustard",
  COW_DANDER: "Allergy to cow dander",
  CHICKEN: "Allergy to chicken",
  OYSTER: "Allergy to oyster",
  ETHYL_ALCOHOL: "Allergy to ethyl alcohol",
  YEAST: "Allergy to yeast",
  RUST: "Allergy to rust",
  RUBBER: "Allergy to rubber",
  OATS: "Allergy to oats",
  ALMOND_OIL: "Allergy to almond oil",
  CAFFEIN: "Allergy to caffein",
  SOYA: "Allergy to soya",
  SEAFOOD: "Allergy to seafood",
  //
  LOVASTATIN: "Allergy to lovastatin",
  PITAVASTATIN: "Allergy to pitavastatin",
  //
  BEE_VENOM: "Allergy to bee venom",
  SUFENTANIL: "Allergy to sufentanil",
  NEVIRAPIN: "Allergy to nevirapin",
  DARUNAVIR: "Allergy to darunavir",
  POLLEN: "Allergy to pollen",
  GAUZE: "Allergy to gauze",
  WASP_VENOM: "Allergy to wasp venom",
  PLANT_FIBER: "Allergy to plant fiber",
  MOLLUSK: "Allergy to mollusk",
  TERIPARATIDE: "Allergy to teriparatide",
  SPIDER_VENOM: "Allergy to spider venom",
  IMIPENEM: "Allergy to imipenem",
  SCORPION_VENOM: "Allergy to scorpion venom",
  MEROPENEM: "Allergy to meropenem",
  ANIMAL_HAIR: "Allergy to animal hair",
  ALUMINIUM: "Allergy to aluminium",
};